name: "Set Bot Git User"
description: "set bot git user or custom user"
branding:
  icon: "user-plus"
  color: gray-dark
inputs:
  name:
    description: "git config user.name"
    required: false
    default: github-actions[bot]
  email:
    description: "git config user.email"
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
runs:
  using: "composite"
  steps:
    - name: git config user
      env:
        NAME: ${{ inputs.name }}
        EMAIL: ${{ inputs.email }}
      shell: bash
      run: |
        git config user.name $NAME
        git config user.email $EMAIL
        
