name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
#  schedule:

jobs:
  runners:
    runs-on: ubuntu-latest
#    outputs:
    steps:
      - name: step1
#        id: stepFirst
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "step1"


