name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
#  schedule:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - uses: ./
      - name: test default user and email
        run: |
          test "$(git config user.name)" = "github-actions[bot]" 
          test "$(git config user.email)" = "41898282+github-actions[bot]@users.noreply.github.com"
          echo "test default user and email passed $(git config user.name)"

      - uses: ./
        with:
          name: "custom user"
          email: "custom email"
      - name: test custom user and email
        run: |
          test "$(git config user.name)" = "custom user" 
          test "$(git config user.email)" = "custom email"
          echo "test custom user and email passed $(git config user.name)"

  test-passing:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - run: echo "test-passing"



